spring:
  application:
    name: AuthorizationServer
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.oauth2.server.authorization: TRACE